In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import make_classification

In [3]:
x,y=make_classification(n_samples=1000,n_features=10,n_redundant=2,n_informative=8,n_classes=3)

In [4]:
df=pd.DataFrame(x)

In [5]:
df['target']=y

In [6]:
df.head()

,0,1,2,3,4,5,6,7,8,9,target
0,-5.362780,-5.847769,-0.388342,2.733280,0.840532,-0.541234,-0.373955,-2.349073,-4.717966,-0.108289,2
1,0.164388,-0.306039,0.821046,0.331487,0.999630,-1.103319,0.746255,3.112640,-0.180204,-1.894800,2
2,-2.318817,3.727800,1.168910,-1.933567,1.897844,0.515338,0.921472,0.584214,0.077796,1.006269,1
3,-0.272999,-4.262886,-1.015085,2.206091,0.156594,1.144990,-4.417434,0.638407,-2.391636,1.236455,2
4,1.740819,0.590394,1.593615,-3.644712,0.586571,-2.414156,-3.516636,0.441239,-2.148248,-0.538741,2

In [7]:
df.isnull().sum()

0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
target    0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.3,random_state=42)

In [10]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier

In [11]:
gbm=GradientBoostingClassifier()

In [12]:
param_grid = {
    "n_estimators": [50, 100, 200],
    "learning_rate": [0.01, 0.1, 0.5, 1.0],
    "max_depth": [1, 2, 3,4,5,6,7],
    "min_samples_split":[2,3,5,6,10,7],
    "min_samples_leaf":[2,4,6,8,10]
}

In [13]:
from sklearn.model_selection import GridSearchCV

In [14]:
grid = GridSearchCV(
    estimator=gbm,
    param_grid=param_grid,
    cv=3,
    scoring="accuracy",
    n_jobs=-1,verbose=1
)

In [15]:
grid.fit(x_train,y_train)

Fitting 3 folds for each of 2520 candidates, totalling 7560 fits

GridSearchCV(cv=3, estimator=GradientBoostingClassifier(), n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.1, 0.5, 1.0],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7],
                         'min_samples_leaf': [2, 4, 6, 8, 10],
                         'min_samples_split': [2, 3, 5, 6, 10, 7],
                         'n_estimators': [50, 100, 200]},
             scoring='accuracy', verbose=1)

In [16]:
print(grid.best_params_)
print(grid.best_score_)

{'learning_rate': 1.0, 'max_depth': 7, 'min_samples_leaf': 10, 'min_samples_split': 10, 'n_estimators': 100}
0.8057787070662608

In [17]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [18]:
from sklearn.datasets import make_regression

In [19]:
x,y=make_regression(n_samples=1000,n_features=10,noise=0.3,random_state=42)

In [21]:
data=pd.DataFrame(x)
data['target']=y

In [23]:
data.head()

,0,1,2,3,4,5,6,7,8,9,target
0,1.575876,0.891863,-0.726774,-0.047799,-0.657035,-1.113295,-0.877617,0.994558,-0.299696,-0.761760,-62.877668
1,0.535459,1.266661,-1.779875,1.209010,-0.113158,-0.971062,1.064171,-0.555273,0.741320,-0.987523,108.458759
2,-0.686279,0.157128,0.145836,-1.432671,-0.666849,0.176190,0.585299,0.197917,-0.404362,-0.607472,-115.386644
3,0.925282,0.395914,0.676357,0.168651,1.574147,-0.117172,-0.037687,-0.345907,0.895796,-0.837381,36.672166
4,-0.558922,1.073632,1.565524,0.377212,0.132970,-1.026515,-0.065750,-0.700121,-1.523187,1.195047,131.120599

In [24]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor

In [25]:
gbm=GradientBoostingRegressor()

In [26]:
param_grid = {
    "loss":["squared_error", "absolute_error", "huber", "quantile"],
    "n_estimators": [ 100, 200],
    "learning_rate": [0.01, 0.1, 0.5, 1.0],
    "max_depth": [ 2, 3,4,5,6,7],
    "min_samples_split":[2,3,5,6,10,7],
    "min_samples_leaf":[2,4,6,8,10]
}

In [29]:
grid = GridSearchCV(
    estimator=gbm,
    param_grid=param_grid,
    cv=3,
    scoring="accuracy",
    n_jobs=-1,verbose=1
)

In [30]:
grid.fit(x_train,y_train)

Fitting 3 folds for each of 5760 candidates, totalling 17280 fits

KeyboardInterrupt:

In [ ]:
print(grid.best_params_)
print(grid.best_score_)