In [39]:
import pandas as pd
import numpy as np

In [40]:
data=pd.read_csv("agr_en_train.csv",header=None)

In [41]:
data.head()

,0,1,2
0,facebook_corpus_msr_1723796,Well said sonu..you have courage to stand agai...,OAG
1,facebook_corpus_msr_466073,"Most of Private Banks ATM's Like HDFC, ICICI e...",NAG
2,facebook_corpus_msr_1493901,"Now question is, Pakistan will adhere to this?",OAG
3,facebook_corpus_msr_405512,Pakistan is comprised of fake muslims who does...,OAG
4,facebook_corpus_msr_1521685,"??we r against cow slaughter,so of course it w...",NAG

In [42]:
data.drop(columns=[0],inplace=True)

In [43]:
data.head()

                                                   1    2
0  Well said sonu..you have courage to stand agai...  OAG
1  Most of Private Banks ATM's Like HDFC, ICICI e...  NAG
2     Now question is, Pakistan will adhere to this?  OAG
3  Pakistan is comprised of fake muslims who does...  OAG
4  ??we r against cow slaughter,so of course it w...  NAG

In [44]:
data=data.rename(columns={1:"text",2:"label"})

In [45]:
data.head()

                                                text label
0  Well said sonu..you have courage to stand agai...   OAG
1  Most of Private Banks ATM's Like HDFC, ICICI e...   NAG
2     Now question is, Pakistan will adhere to this?   OAG
3  Pakistan is comprised of fake muslims who does...   OAG
4  ??we r against cow slaughter,so of course it w...   NAG

In [46]:
data['text']=data['text'].str.lower()

In [47]:
data.head(2)

                                                text label
0  well said sonu..you have courage to stand agai...   OAG
1  most of private banks atm's like hdfc, icici e...   NAG

In [25]:
pip install contractions

Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.3.0-cp313-cp313-win_amd64.whl.metadata (14 kB)
Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Downloading anyascii-0.3.3-py3-none-any.whl (345 kB)
Downloading pyahocorasick-2.3.0-cp313-cp313-win_amd64.whl (35 kB)
Installing collected packages: pyahocorasick, anyascii, textsearch, contractions

   ---------- ----------------------------- 1/4 [anyascii]
   ---------- ----------------------------- 1/4 [anyascii]
   ---------- ----------------------------- 1/4 [anyascii]
   ---------- ----------------------------- 1/4 [anyascii]
   ---------- ----------------------------- 1/4 [anyascii]
   ---------- ----------------------------- 1/4 [anyascii]
   -------------------- ------------------- 2/4 [textsearch]
   ---------------------------------------- 4/4 [contractions]

Successfully installed anyascii-0.3.3 contractions-0.1.73 pyahocorasick-2.3.0 textsearch-0.0.24
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [48]:
import contractions

In [49]:
data['text']=data['text'].apply(lambda x:contractions.fix(x))

In [50]:
data.head()

                                                text label
0  well said sonu..you have courage to stand agai...   OAG
1  most of private banks atm's like hdfc, icici e...   NAG
2     now question is, pakistan will adhere to this?   OAG
3  pakistan is comprised of fake muslims who does...   OAG
4  ??we r against cow slaughter,so of course it w...   NAG

In [51]:
#remove url
data['text']=data['text'].str.replace(r"http\S+|www\S+|https\S+","",regex=True)

In [52]:
data.head()

                                                text label
0  well said sonu..you have courage to stand agai...   OAG
1  most of private banks atm's like hdfc, icici e...   NAG
2     now question is, pakistan will adhere to this?   OAG
3  pakistan is comprised of fake muslims who does...   OAG
4  ??we r against cow slaughter,so of course it w...   NAG

In [53]:
#remove punctuation
import string

In [54]:
data['text']=data['text'].str.replace(f"[{string.punctuation}]","",regex=True)

In [55]:
data.head()

                                                text label
0  well said sonuyou have courage to stand agains...   OAG
1  most of private banks atms like hdfc icici etc...   NAG
2       now question is pakistan will adhere to this   OAG
3  pakistan is comprised of fake muslims who does...   OAG
4  we r against cow slaughterso of course it will...   NAG

In [36]:
pip install textblob

Collecting textblob
  Downloading textblob-0.19.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: nltk>=3.9 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from nltk>=3.9->textblob) (8.1.8)
Requirement already satisfied: joblib in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from nltk>=3.9->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from nltk>=3.9->textblob) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Downloading textblob-0.19.0-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/624.3 kB ? eta -:--:--
   --------------------------------- ------ 524.3/624.3 kB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 624.3/624.3 kB 816.6 kB/s  0:00:01
Installing collected packages: textblob
Successfully installed textblob-0.19.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [37]:
from textblob import TextBlob

In [38]:
# data['text']=data['text'].apply(lambda x: str(TextBlob(x).correct()))

KeyboardInterrupt:

In [ ]:
pip install fuzzywuzzy

In [56]:
import nltk

In [57]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Mcc\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [58]:
from nltk.tokenize import word_tokenize

In [59]:
data['tokens']=data['text'].apply(word_tokenize)

In [60]:
data.head()

,text,label,tokens
0,well said sonuyou have courage to stand agains...,OAG,"[well, said, sonuyou, have, courage, to, stand..."
1,most of private banks atms like hdfc icici etc...,NAG,"[most, of, private, banks, atms, like, hdfc, i..."
2,now question is pakistan will adhere to this,OAG,"[now, question, is, pakistan, will, adhere, to..."
3,pakistan is comprised of fake muslims who does...,OAG,"[pakistan, is, comprised, of, fake, muslims, w..."
4,we r against cow slaughterso of course it will...,NAG,"[we, r, against, cow, slaughterso, of, course,..."

In [65]:
pip install spacy

Requirement already satisfied: spacy in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (0.21.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (2.12.5)
Requirement already satisfied: jinja2 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (3.1.4)
Requirement already satisfied: setuptools in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (75.3.0)
Requirement already satisfied: packaging>=20.0 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from spacy) (24.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.8.30)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: colorama in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (8.1.8)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.4.1)
Requirement already satisfied: wrapt in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (1.17.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mcc\appdata\local\programs\python\python313\lib\site-packages (from jinja2->spacy) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [68]:
import spacy

In [70]:
python -m spacy download en_core_web_sm

SyntaxError: invalid syntax (581980377.py, line 1)

In [72]:
def remove_stopwords(tokens):
    return [token for token in tokens if token.lower() not in stopwords]

In [74]:
from nltk.corpus import stopwords

import nltk
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Mcc\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [75]:
data['clean_tokens'] = data['tokens'].apply(remove_stopwords)

TypeError: argument of type 'WordListCorpusReader' is not iterable